api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /

core:
    resource: "@CoreBundle/Resources/config/routing.php"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
