<?php

namespace ApiBundle\Repository;

/**
 * TesterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TesterRepository extends \Doctrine\ORM\EntityRepository
{
}
